export const ADD_PENDING_ACTION = 'global/AddPendingAction'
export const REMOVE_PENDING_ACTION = 'global/RemovePendingAction'
export const SET_LOGIN = 'global/SetLogin'
export const SET_USER = 'global/SetUser'
export const UPDATE_USER = 'global/UpdateUser'
export const RESET_STATE = 'global/ResetState'
export const FETCH_EVENTS = 'global/FetchEvents'
export const FETCH_EVENTS_SUCCESS = 'global/FetchEventsSuccess'